
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://xx.xx.xx.xx:3306/commonProject?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: xxxxxx
      password: xxxxxx
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j2
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    servlet:
      path: /commonProject
    static-path-pattern: /static/**
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
mybatis:
  mapper-locations: classpath*:mapper/**Mapper.xml
  type-aliases-package: com.supervons.cpj.entity
